name: Lint Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR Title
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            build
            ci
            docs
            feat
            fix
            perf
            refactor
            test
          requireScope: false
